services:
  - type: web
    name: SketchCollab-ws-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: / 
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
